FROM node:8-alpine

WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
COPY ./src ./src
RUN npm run build
COPY ./client ./client
RUN cd client && npm install && npm run build

FROM node:8-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY --from=0 /usr/src/app/build ./build
COPY ./templates ./templates
COPY ./src/config.json ./build
EXPOSE 80
CMD npm start