
POST http://localhost:5002/api/auth/register
Content-Type: application/json

{
    "email": "someone@something.com",
    "password": "fooey"
}

###

# Copy token from console output of previous request.

POST http://localhost:5002/api/auth/confirm
Content-Type: application/json

{
    "email": "someone@something.com",
    "token": "aa925b17-b853-420d-815f-c0cd855338a4"
}

###

POST http://localhost:5002/api/auth/authenticate
Content-Type: application/json

{
    "email": "someone@something.com",
    "password": "fooey"
}

###

# Copy token from response of previous request.

POST http://localhost:5002/api/auth/validate
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmVhZmQyNDcxZGU2NDAwNTY5MmU0NmMiLCJ2IjoxLCJleHBpcnkiOiIyMDIxLTAxLTI5VDA5OjU2OjIxLjg0MFoiLCJpYXQiOjE2MDkyMzU3ODF9.HnsABDgwBVw-i9zY6CIkrXOZhrdBYzvb_MY5YzieiaY"
}