
POST http://localhost:5002/api/auth/register
Content-Type: application/json

{
    "email": "someone@something.com",
    "password": "fooey"
}

###

# Copy token from console output of previous request.

POST http://localhost:5002/api/auth/confirm
Content-Type: application/json

{
    "email": "someone@something.com",
    "token": "b9c8b158-9bc3-4fe8-9b35-c3c66878bebc"
}

###

POST http://localhost:5002/api/auth/authenticate
Content-Type: application/json

{
    "email": "someone@something.com",
    "password": "fooey"
}

###

# Copy token from response of previous request.

POST http://localhost:5002/api/auth/validate
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmVkMTRlNjAzNTAzNjAwNmM5NjZmY2YiLCJ2IjoxLCJleHBpcnkiOiIyMDIxLTAxLTMxVDAwOjAyOjA2LjAxMloiLCJpYXQiOjE2MDkzNzI5MjZ9.LY-CJ38kBcxJjK09lhmhmpQIL-5HHEnNULiSEQigsY4"
}

###

# Copy token from response of previous request.

POST http://localhost:5002/api/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmVkMTRlNjAzNTAzNjAwNmM5NjZmY2YiLCJ2IjoxLCJleHBpcnkiOiIyMDIxLTAxLTMxVDAwOjAyOjA2LjAxMloiLCJpYXQiOjE2MDkzNzI5MjZ9.LY-CJ38kBcxJjK09lhmhmpQIL-5HHEnNULiSEQigsY4"
}