#
# Help
#
# Docs:
# https://docs.docker.com/compose/compose-file
#
# The z/Z flags for volumes:
# https://stackoverflow.com/a/35222815/25868
#

version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "6000:27017"
    restart: always

  mailer:
    image: mailer
    build: 
      context: ../mock-mailer
      dockerfile: Dockerfile-dev
    container_name: mailer
    volumes:
      - ../tmp/mock-mailer/npm-cache:/root/.npm:z
      - ../mock-mailer/src:/usr/src/app/src:z
    ports:
     - "6001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"

